blank_issues_enabled: false
contact_links:
  - name: SAP Cloud SDK for AI Java issues
    url: https://github.com/SAP/ai-sdk-java/issues/new/choose
    about: Please report issues concerning the SAP Cloud SDK for AI Java.
  - name: SAP Cloud SDK for AI JavaScript / TypeScript issues
    url: https://github.com/SAP/ai-sdk-js/issues/new/choose
    about: Please report issues concerning the SAP Cloud SDK for AI JavaScript / TypeScript here.
