extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://www.sapbrandtools.com/naming-center/'
level: error
ignorecase: false
swap:
  (?:[^\s]*) ?(?:[^\s]*) ?SDKs?: SAP Cloud SDK
  (?:[^\s]*) ?Cloud Platform: SAP Cloud Platform
  (?:[^\s]*) ?S/?4/? ?HANA: SAP S/4HANA
  (?:[^\s]*) ?Success ?Factors: SAP SuccessFactors
  SFSF: SAP SuccessFactors
  C4C: SAP Cloud for Customer
  (?:[^\s]*) ?Fieldglass: SAP Fieldglass
  (?:[^\s]*) ?Ariba: SAP Ariba
  (?:[^\s]*) ?Concur: SAP Concur
  # SAP S/4HANA OnPremise: SAP S/4HANA on-premise edition
