extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://www.sapbrandtools.com/naming-center/'
level: error
ignorecase: false
swap:
  (?:[^\s]*) ?(?:[^\s]*) ?SDKs?: SAP Cloud SDK
  (?:[^\s]*) ?Cloud Platform: SAP Cloud Platform
  (?:[^\s]*) ?S/?4/? ?HANA: SAP S/4HANA
  (?:[^\s]*) ?Success ?Factors: SAP SuccessFactors
  SFSF: SAP SuccessFactors
  C4C: SAP Cloud for Customer
  (?:[^\s]*) ?Fieldglass: SAP Fieldglass
  (?:[^\s]*) ?Ariba: SAP Ariba
  (?:[^\s]*) ?Concur: SAP Concur
  (?:[^\s]*) ?BTP: SAP BTP
  (?:[^\s]*) ?cloud [fF]oundry: Cloud Foundry
  (?:[^\s]*) ?[cC]loud foundry: Cloud Foundry
  (?:[^\s]*) ?[oO]n[pP]remise[s]*: [oO]n-[pP]remise #No without -
  (?:[^\s]*) ?[oO]n-[pP]remises: [oO]n-[pP]remise #No s in the end
  (?:[^\s]*) ?[oO]n[-]*[pP]rem: [oO]n-[pP]remise #No OnPrem short term
  # SAP S/4HANA OnPremise: SAP S/4HANA on-premise edition
  (?:)[Tt]ype[ -]*[Ss]cript: TypeScript
  (?:[^\s]*) ?[API|api] [hH]ub: SAP API Business Hub
