extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://www.sapbrandtools.com/naming-center/'
level: error
ignorecase: false
swap:
  (?:[^\s]*) ?(?:[^\s]*) ?SDK: SAP Cloud SDK
  (?:[^\s]*) ?Cloud Platform: SAP Cloud Platform
  (?:[^\s]*) ?S/?4/? ?HANA: SAP S/4HANA
  # SAP S/4HANA OnPremise: SAP S/4HANA on-premise edition
