name: Linting
on:
  pull_request:
    branches: [main]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vale
        uses: errata-ai/vale-action@v1.3.0
        with:
          files:
            - .github
            - docs
            - CODE_OF_CONDUCT.md
            - CONTRIBUTING.md
            - README.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
